news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('timeline/', views.timeline_view, name='timeline'),
    path('create/', views.create_view, name='create'),
    path('artikel/<int:post_id>', views.artikel_view, name='artikel'),
    path('artikel/<int:post_id>/delete', views.delete_view, name='delete'),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('Training/', views.training, name='training'),
    path('Kontakt/', views.contact_view, name='contact'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('Maischwimmen/', views.maischwimmen, name='ms'),
    path('Trainingslager/', views.trainingslager, name='tl'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class NewsPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    header = models.CharField(max_length=250)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('news:artikel', kwargs={'post_id': self.id})

web/models.py
from django.db import models


class Wettkampf(models.Model):
    Ort = models.CharField(max_length=250)
    Datum = models.DateTimeField()

news/forms.py
from django import forms
from .models import NewsPost


class PostForm(forms.ModelForm):

    class Meta:
        model = NewsPost
        fields = ['header', 'created_at', 'content']
        labels = {
            'header': 'Überschrift',
            'created_at': 'Datum als JJJJ-MM-TT',
            'content': 'Inhalt',
        }
        widgets = {

        }

web/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, label='Benutzername:')
    password = forms.CharField(max_length=35, label='Password:', widget=forms.PasswordInput)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label='Benutzername:')
    password = forms.CharField(max_length=35, label='Password:', widget=forms.PasswordInput)


class ContactForm(forms.Form):
    Name = forms.CharField(max_length=250, required=True)
    Email = forms.EmailField(required=True)
    Nachricht = forms.CharField(required=True, widget=forms.Textarea)

news/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import PostForm
from .models import NewsPost


def index(request):
    return render(request, 'news/index.html')


def timeline_view(request):
    post_form = PostForm()
    posts = NewsPost.objects.order_by('-created_at')
    return render(request, 'news/timeline.html', {'posts': posts, 'post_form': post_form})


@login_required
@require_POST
def create_view(request):
    post_form = PostForm(request.POST)
    if post_form.is_valid():
        post = post_form.save(commit=False)
        post.user = request.user
        post.save()
    return redirect('news:timeline')


@login_required
@require_POST
def delete_view(request, post_id):
    post = get_object_or_404(NewsPost, id=post_id, user=request.user)
    post.delete()
    return redirect('news:timeline')


def artikel_view(request, post_id):
    post = get_object_or_404(NewsPost, id=post_id)
    return render(request, 'news/artikel.html', {'post': post})

web/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse

from django.conf import settings
from .models import Wettkampf
from .forms import RegisterForm, LoginForm, ContactForm
from django.core.mail import EmailMessage, send_mail
from django.template.loader import get_template


def index(request):
    wks = Wettkampf.objects.order_by('Datum')
    return render(request, 'web/index.html', {'wks': wks})


def training(request):
    return render(request, 'web/training.html')


def maischwimmen(request):
    return render(request, 'web/maischwimmen.html')


def trainingslager(request):
    return render(request, 'web/trainingslager.html')


def contact_view(request):
    contact_form = ContactForm
    if request.method == 'POST':
        form = contact_form(request.POST)
        if form.is_valid():
            contact_name = request.POST.get('Name')
            contact_email = request.POST.get('Email')
            form_content = request.POST.get('Nachricht')

            subject = 'Kontaktformluar Erhalten'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [settings.DEFAULT_FROM_EMAIL]

            context = {'contact_name': contact_name, 'contact_email': contact_email, 'form_content': form_content}

            contact_message = get_template('contact_template.txt').render(context)

            send_mail(subject, contact_message, from_email, to_email, fail_silently=True)

            return redirect('web:index')
    return render(request, 'web/kontakt.html', {'contact_form': contact_form})


def register_view(request):
    register_form = RegisterForm()
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            User.objects.create_user(username=username, password=password)
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('news:timeline', kwargs={'username': request.user.username}))
    return render(request, 'web/register.html', {'register_form': register_form})


def login_view(request):
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('news:timeline'))
    return render(request, 'web/login.html', {'login_form': login_form})


def logout_view(request):
    logout(request)
    return redirect(reverse('web:index'))


news/templates/news/artikel.html
{% extends 'news/base.html' %}

{% block style %}<link rel="stylesheet" href='/static/css/artikel.css' type="text/css">{% endblock %}

{% block mainForm %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">{{ post.header }}</h1>
                <p class="card-text">{{ post.created_at | date:"d. F Y" }}</p>
                <p class="card-text">{{ post.content | linebreaks }}</p>
                {% if post.user == request.user %}
                <form action="{% url 'news:delete' post.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm">Löschen</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
    <meta charset="UTF-8">
	<link rel="icon" type="image/png" href="{% static 'pics/icon.png' %}">

	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href='/static/css/base.css' type="text/css">
	{% block style %}{% endblock %}
</head>

    <body>
		<div class="container">
			<header>
				<img src="{% static 'news/pics/banner.png' %}" class="img-fluid" alt="Responsive image">
			</header>
			<nav class="navbar navbar-dark bg-dark">
				<span class="navbar-text">
					<a href="{% url 'web:index' %}" class="btn btn-dark">Home</a>
					<a href="{% url 'web:training' %}" class="btn btn-dark">Training</a>
					<a href="{% url 'web:contact' %}" class="btn btn-dark">Kontakt</a>
					<a href="{% url 'news:timeline' %}" class="btn btn-danger">Artikel</a>
					<a href="termine.html" class="btn btn-dark">Termine</a>
				</span>
			</nav>

			{% block mainForm %}

			{% endblock %}

		</div>
		<footer>
			<p><a href="impressum.html" class="btn btn-outline-danger btn-sm">Impressum</a></p>
			{% if request.user.is_authenticated %}
			<p><a href="{% url 'web:logout' %}"class="btn btn-outline-danger btn-sm">Logout</a></p>
			{% else %}
			<p><a href="{% url 'web:login' %}"class="btn btn-outline-danger btn-sm">Login</a></p>
			{% endif %}
		</footer>
	</body>
</html>

news/templates/news/timeline.html
{% extends 'news/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block style %}<link rel="stylesheet" href='/static/css/timeline.css' type="text/css">{% endblock %}


{% block mainForm %}
    <div class="container">


        <h1>Artikel</h1>

        {% if request.user.is_authenticated %}
        <form action="{% url 'news:create' %}" method="post" id="create">
            {% bootstrap_form post_form %}
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Senden</button>
        </form>
        {% endif %}

        {% for post in posts %}
            <div class="row">
                <div class="col-12">
                    <div id="Artikel" class="card">
                         <div class="card-body">
                             <div class="row">
                                 <div class="col-4">
                                     <p id="datum">{{ post.created_at | date:"d. F Y" }}</p>
                                 </div>
                                 <div class="col-8">
                                     <h3 class="card-title">{{ post.header }}</h3>
                                     <p id="inhalt" class="card-text">{{ post.content }}</p>
                                     <a href="{{ post.get_absolute_url }}" class="btn btn-danger btn-sm">mehr</a>
                                     {% if post.user == request.user %}
                                     <form action="{% url 'news:delete' post.id %}" method="post" id="löschen">
                                         {% csrf_token %}
                                         <button type="submit" class="btn btn-outline-danger btn-sm">Löschen</button>
                                     </form>
                                     {% endif %}
                                 </div>
                             </div>
                          </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}



web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
    <meta charset="UTF-8">
	<link rel="icon" type="image/png" href='/static/img/icon.png'>
    <title>{% block title%} Frankenberger Schwimmverein{% endblock %}</title>


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href='/static/css/base.css' type="text/css">
	{% block style %}{% endblock %}

</head>

    <body>
			<div class="container">
				<header>
					<img src="/static/img/banner.png" class="img-fluid" alt="Responsive image">
				</header>

				{% block nav %}
				<nav class="navbar navbar-dark bg-dark">
					<span class="navbar-text">
							<a href="{% url 'web:index' %}" class="btn btn-danger">Home</a>
							<a href="{% url 'web:training' %}" class="btn btn-dark">Training</a>
							<a href="{% url 'web:contact' %}" class="btn btn-dark">Kontakt</a>
							<a href="{% url 'news:timeline' %}" class="btn btn-dark">Artikel</a>
							<a href="termine.html" class="btn btn-dark">Termine</a>
					</span>
				</nav>
				{% endblock %}


				{% block mainForm %}
				{% endblock %}



			</div>
			<footer>
                <p><a href="impressum.html" class="btn btn-outline-danger btn-sm">Impressum</a></p>
				{% if request.user.is_authenticated %}
				<p><a href="{% url 'web:logout' %}"class="btn btn-outline-danger btn-sm">Logout</a></p>
				{% else %}
				<p><a href="{% url 'web:login' %}"class="btn btn-outline-danger btn-sm">Login</a></p>
				{% endif %}
            </footer>
		</body>
</html>

web/templates/web/index.html
{% extends 'web/base.html' %}

{% load bootstrap4 %}
{% load static %}

{% block titel %}Frankenberger Schwimmverein{% endblock %}

{% block style %}
<link rel="stylesheet" href='/static/css/index.css' type="text/css">
{% endblock %}

{% block nav %}
    <nav class="navbar navbar-dark bg-dark">
        <span class="navbar-text">
            <a href="{% url 'web:index' %}" class="btn btn-danger">Home</a>
            <a href="{% url 'web:training' %}" class="btn btn-dark">Training</a>
            <a href="{% url 'web:contact' %}" class="btn btn-dark">Kontakt</a>
            <a href="{% url 'news:timeline' %}" class="btn btn-dark">Artikel</a>
            <a href="termine.html" class="btn btn-dark">Termine</a>
        </span>
    </nav>
{% endblock %}


{% block mainForm %}
    <div class="banner">
        <img class="d-block w-100" src="/static/img/slider1.png" alt="first slide">
    </div>



    <div id="main" class="row">
        <div class="col-9">
            <h1>FSV</h1>
        </div>
    
        <div class="col-3">
            <div id="wettkämpfe" class="card">
                <h3 class="card-title">Wettkämpfe</h3>


                {% for wk in wks %}
                     <div class="row">
                        <div class="col-12">
                            <div id="wettkampf" class="card">
                                <p id="datum">{{ wk.Datum | date:"d.m.Y" }}</p>
                                <p id="wk" >{{ wk.Ort }}</p>
                            </div>
                        </div>

                     </div>
                {% endfor %}
            </div>
            <a id="aktuelles" class="btn btn-danger btn-lg btn-block" href="{% url 'web:ms' %}">Maischwimmen</a>
            <a id="aktuelles" class="btn btn-danger btn-lg btn-block" href="{% url 'web:tl' %}">Trainingslager</a>
        </div>
    </div>

{% endblock %}

web/templates/web/kontakt.html
{% extends 'web/base.html' %}

{% load bootstrap4 %}
{% load static %}

{% block titel %}Frankenberger Schwimmverein{% endblock %}

{% block style %}
<link rel="stylesheet" href='/static/css/login.css' type="text/css">
{% endblock %}


{% block nav %}
    <nav class="navbar navbar-dark bg-dark">
        <span class="navbar-text">
            <a href="{% url 'web:index' %}" class="btn btn-dark">Home</a>
            <a href="{% url 'web:training' %}" class="btn btn-dark">Training</a>
            <a href="{% url 'web:contact' %}" class="btn btn-danger">Kontakt</a>
            <a href="{% url 'news:timeline' %}" class="btn btn-dark">Artikel</a>
            <a href="termine.html" class="btn btn-dark">Termine</a>
        </span>
    </nav>
{% endblock %}


{% block mainForm %}
	<div class="col-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
        <h1>Kontakt</h1>
        <p>Hier können sie Kontakt mit uns aufnehmen</p>

        <form role="form" method="post" action="">
            {% csrf_token %}
            {% bootstrap_form contact_form %}
            <button id="button" type="submit" class="btn btn-danger">Senden</button>
        </form>
    </div>
    <div id="pusher"></div>
{% endblock %}

web/templates/web/login.html
{% extends 'web/base.html' %}
{% load bootstrap4 %}

{% block title %} FSV - Login {% endblock %}

{% block style %}
<link rel="stylesheet" href='/static/css/login.css' type="text/css">
{% endblock %}

{% block mainForm %}
    <div class="col-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
        <h1>Login</h1>
        <p>Dieser Bereich ist nur für Befugte</p>

        <form method="post" action="">
            {% csrf_token %}
            {% bootstrap_form login_form %}
            <button id="button" type="submit" class="btn btn-danger">Login</button>
        </form>
    </div>
    <div id="pusher"></div>
{% endblock %}

web/templates/web/maischwimmen.html
{% extends 'web/base.html' %}
{% load bootstrap4 %}

{% block title %} FSV - Login {% endblock %}

{% block style %}
<link rel="stylesheet" href='/static/css/maischwimmen.css' type="text/css">
{% endblock %}

{% block mainForm %}
    <div class="row">
        <div class="col-12">
            <h1>Maischwimmen</h1>
        </div>
    </div><
{% endblock %}

web/templates/web/register.html
{% extends 'web/base.html' %}
{% load bootstrap4 %}

{% block titel %}FSV - Registrieren{% endblock %}

{% block mainForm %}

    <h1>Registrieren</h1>
    <p>Dieser Bereich ist nur für Befugte</p>

    <form method="post" action="">
        {% csrf_token %}
        {% bootstrap_form register_form %}
        <button id="button" type="submit" class="btn btn-danger">Erstellen</button>
    </form>

{% endblock %}

web/templates/web/training.html
{% extends 'web/base.html' %}
{% load static %}
{% block title%} FSV - Training {% endblock %}


{% block style %}<link rel="stylesheet" href='/static/css/training.css' type="text/css">{% endblock %}



{% block nav %}
				<nav class="navbar navbar-dark bg-dark">
					<span class="navbar-text">
							<a href="{% url 'web:index' %}" class="btn btn-dark">Home</a>
							<a href="{% url 'web:training' %}" class="btn btn-danger">Training</a>
							<a href="{% url 'web:contact' %}" class="btn btn-dark">Kontakt</a>
							<a href="{% url 'news:timeline' %}" class="btn btn-dark">Artikel</a>
							<a href="termine.html" class="btn btn-dark">Termine</a>
					</span>
				</nav>
				{% endblock %}

{% block mainForm %}

    <div class="container">
    	<h1>Trainingszeiten</h1>
		<p><h3>Stand 20.01.2018</h3></p>
		<p><h3>In der Hallenbadsaison 2017/2018 sind die Trainingszeiten wie folgt:</h3></p>
		<table class="table table-bordered table-hover table-responsive-xl">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Uhrzeit</th>
					<th scope="col">Montag</th>
					<th scope="col">Dienstag</th>
					<th scope="col">Mittwoch</th>
					<th scope="col">Donnerstag</th>
					<th scope="col">Freitag</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td scope="row">13:00-14:45</td>
					<td>---------</td>
					<td>Schwimmanfänger</td>
					<td>---------</td>
					<td>---------</td>
					<td>Schwimmanfänger</td>
				</tr>
				<tr>
					<td scope="row">15:00-16:30</td>
					<td>---------</td>
					<td>---------</td>
					<td>---------</td>
					<td>---------</td>
					<td>L1-L3</td>
				</tr>
				<tr>
					<td scope="row">17:00-18:00</td>
					<td>Nachwuchsgruppen L2/L3</td>
					<td>---------</td>
					<td>L2/L3</td>
					<td>L1-L3 <p>in Battenberg</p></td>
					<td>---------</td>
				</tr>
				<tr>
					<td scope="row">18:00-19:00</td>
					<td>L1-L3 + Schwimmanfänger</td>
					<td>---------</td>
					<td>L1-L3</td>
					<td>L1-L3 <p>in Battenberg</p></td>
					<td>---------</td>
				</tr>
				<tr>
					<td scope="row">19:00-20:00</td>
					<td>L1</td>
					<td>---------</td>
					<td>L1-L3</td>
					<td>---------</td>
					<td>---------</td>
		        </tr>
					<td scope="row">20:00-21:00</td>
					<td>Erwachsene/Triathlon</td>
					<td>---------</td>
					<td>Erwachsene/Triathlon</td>
					<td>---------</td>
					<td>---------</td>
				</tr>
			</tbody>

		</table>
		<p id="p1">Die Uhrzeiten sind reine Trainingszeiten. Bitte immer 10 Minuten vorher da sein!<p>
		<p id="pEnde">Zusätzlich findet an wettkampffreien Samstagen Training von 12:30 - 14:30 Uhr in Battenberg statt.</p>
	</div>

{% endblock %}

web/templates/web/trainingslager.html
{% extends 'web/base.html' %}
{% load bootstrap4 %}

{% block title %} FSV - Login {% endblock %}

{% block style %}
<link rel="stylesheet" href='/static/css/trainingslager.css' type="text/css">
{% endblock %}

{% block mainForm %}
    <div class="row">
        <div class="col-12">
            <h1>Trainingslager</h1>
        </div>
    </div>
{% endblock %}